Clean notebook metadata
srstevenson/nb-clean pull request #163
Opened 2022-10-28 16:45 UTC by yasirroni

Add new argument for clean and filter "-M" or "--remove-notebook-metadata" to "remove notebook metadata.

```python
    clean_parser.add_argument(
        "-M",
        "--remove-notebook-metadata",
        action="store_true",
        help="remove notebook metadata",
    )
```

2022-10-30 11:18 UTC, srstevenson commented
As this is branched from #161, I'll wait until that's complete before reviewing this.

2024-05-27 00:23 UTC, yasirroni commented
https://github.com/srstevenson/nb-clean/pull/161 is merged. Please review this branch. I will rebase this branch.

2024-05-27 00:45 UTC, yasirroni commented
After some reading it seems current behavior of nb-clean is cleaning notebook metadata?

2024-05-27 11:35 UTC, srstevenson requested changes
Before we consider merging this, we need to think more about the approach and how to maintain compatibility for existing users.

With this change, there are `--preserve-notebook-metadata` and `--remove-notebook-metadata` arguments which sound as though they are the inverse of one another but do different things and are toggled independently. This is confusing for users, and also for me to maintain.

`--preserve-notebook-metadata`  only checks for and removes the `language_info.version` key from the metadata, whereas the new `--remove-notebook-metadata` argument removes all metadata keys. We need the names to disambiguate this: for example, by renaming `--remove-notebook-metadata` to `--remove-all-notebook-metadata` or similar.

Even if it were named differently, I'm not keen to maintain two flags so easily confused with each other. Perhaps we should deprecate `--preserve-notebook-metadata`? This can be achieved in a sequence of steps across future releases:

- from this change, using `--preserve-notebook-metadata` prints a deprecation warning that the feature will be removed in future
- after the deprecation warning has been present for some time, the flag becomes a no-op that prints a warning saying the feature was removed
- eventually, we remove the flag entirely and passing it will result in an argument parsing error

In addition, please can you run the linters and test suite with `poetry run poe check` and address the issues raised?

2024-05-27 11:35 UTC, srstevenson commented on README.md
> +| Check notebook (ignore notebook metadata)                    |                                                                     | `nb-clean check notebook.ipynb -M/--remove-notebook-metadata`
This doesn't look to be fully rebased: there aren't short flags such as `-i` in the nb-clean 1.6.0 column on `main`.

2024-05-27 11:35 UTC, srstevenson commented on src/nb_clean/__init__.py
> +    remove_notebook_metadata: bool = False,
We now have two arguments to this (and other functions), `remove_notebook_metadata` and `preserve_notebook_metadata`, which both default to `False` which is semantically inconsistent: we need to renconcile this in a way that maintains backward compatibility for existing users of `--preserve-notebook-metadata`.

2024-05-27 11:35 UTC, srstevenson commented on src/nb_clean/__init__.py
> -    if not preserve_notebook_metadata:
Following up on my comment above about having both `remove_notebook_metadata` and `preserve_notebook_metadata`, by removing this `--preserve-notebook-metadata` is no longer observed which breaks existing uses.

2024-05-27 11:35 UTC, srstevenson commented on src/nb_clean/__init__.py
> +            del notebook["metadata"]["language_info"]["version"]
The `else` branch here is a duplicate of the code on line 317, but that code is run under different conditions: it's run if `preserve_notebook_metadata` is False, whereas the code here is run if `remove_notebook_metadata` is False.

2024-05-27 15:00 UTC, yasirroni commented
All updated. Please review.

2024-06-01 18:30 UTC, srstevenson requested changes
Thanks, I've made another round of review -- we're making good progress.

2024-06-01 18:30 UTC, srstevenson commented on README.md
> +By default, `nb-clean` will not delete all notebook metadata. To completely
GitHub doesn't allow commenting on lines not included within the diff in a PR, but we also need to mention `--remove-all-notebook-metadata` where we list the available options in the "Checking" and "Cleaning (interactive)" sections above, starting at lines 61 and 116. In those, we should also make clear that `--preserve-notebook-metadata` only checks for the presence of the `language_info.version` key, to explain how it differs from `--remove-all-notebook-metadata`.

2024-06-01 18:30 UTC, srstevenson commented on README.md
> +| Clean notebook (remove all notebook metadata)                |                                                                     | `nb-clean clean notebook.ipynb -M/--remove-all-notebook-metadata
We don't need to include this in the migration table, as the feature wasn't present in nb-clean 1.6.0 so there's no existing command to migrate from.

2024-06-01 18:30 UTC, srstevenson commented on src/nb_clean/__init__.py
> +        If True, remove all notebooks metadata
```suggestion
        If True, remove all notebook metadata.
```

2024-06-01 18:30 UTC, srstevenson commented on src/nb_clean/__init__.py
> +        If True, also check for the presence of nonempty notebook metadata.
```suggestion
        If True, also check for the presence of any notebook metadata.
```

2024-06-01 18:30 UTC, srstevenson commented on src/nb_clean/__init__.py
> +        command.append("--remove-all-notebook-metadata")
As flagged by Codecov, this addition isn't covered by tests.

2024-06-01 18:30 UTC, srstevenson commented on src/nb_clean/__init__.py
> +    remove_all_notebook_metadata: bool = False,
At the start of the function body, here and for all other functions that take both arguments, let's check that `remove_all_notebook_metadata` and `preserve_notebook_metadata` aren't both `True`, and raise an appropriate exception if so (this combination is impossible to satisfy).

2024-06-01 18:30 UTC, srstevenson commented on src/nb_clean/__init__.py
> +        If True, remove notebook metadata.
```suggestion
        If True, remove all notebook metadata.
```

2024-06-01 18:30 UTC, srstevenson commented on src/nb_clean/cli.py
> +        help="remove notebook metadata",
```suggestion
        help="remove all notebook metadata",
```

2024-06-01 18:30 UTC, srstevenson commented on src/nb_clean/cli.py
> +        help="check for notebook metadata",
```suggestion
        help="check for any notebook metadata",
```

2024-06-01 18:30 UTC, srstevenson commented on src/nb_clean/cli.py
> +        help="remove notebook metadata",
```suggestion
        help="remove all notebook metadata",
```

2024-06-01 18:30 UTC, srstevenson commented on tests/test_check_notebook.py
> +    """Test nb_clean.clean_notebook when removing all notebooks metadata.
```suggestion
    """Test nb_clean.clean_notebook when removing all notebook metadata.
```

2024-06-01 18:30 UTC, srstevenson commented on tests/test_check_notebook.py
> +    `language_info.version` captured by --preserve-notebook-metadata.
This is a useful comment! Suggested tweak to wording:
```suggestion
    The test with `("clean_notebook_with_notebook_metadata", False, True)` is False due
    to `clean_notebook_with_notebook_metadata` containing `language_info.version` detected
    when `preserve_notebook_metadata=False`.
```

2024-06-01 18:30 UTC, srstevenson commented on tests/test_clean_notebook.py
> +    """Test nb_clean.clean_notebook when preserving cell outputs."""
```suggestion
    """Test nb_clean.clean_notebook when removing all notebook metadata."""
```

2024-06-04 03:28 UTC, yasirroni commented
All resolved with 100% coverage. Please review.

2024-06-11 21:58 UTC, srstevenson approved these changes
LGTM, thanks for perservering with this.

2024-06-11 21:59 UTC, merged

2024-06-11 22:09 UTC, srstevenson commented
This change is included in the [nb-clean 3.3.0](https://pypi.org/project/nb-clean/3.3.0/) release.